"""Add partitions by device type in AuthHistoryOrm

Revision ID: a084a8c026f4
Revises: 0298b63bdb82
Create Date: 2023-05-13 18:36:13.686979

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a084a8c026f4'
down_revision = '0298b63bdb82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_device_type', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['id', 'user_device_type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_device_type')

    # ### end Alembic commands ###
