"""Add SocialAccount table

Revision ID: ea1285004993
Revises: a084a8c026f4
Create Date: 2023-05-16 02:37:35.694493

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ea1285004993'
down_revision = 'a084a8c026f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'social_account',
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('social_id', sa.Uuid(), nullable=False),
        sa.Column('social_name', sa.String(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'id'),
        sa.UniqueConstraint('social_id'),
        sa.UniqueConstraint('social_name'),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('social_account')
    # ### end Alembic commands ###
